#!/bin/bash
while [$DECIMAL -lg 16]
do
	if [DECIMAL -lt 10]
	{
		echo $i
	}
	elif [$DECIMAL -ge 10]
	{
		elif [$DECIMAL -ge 15]
        	{
                	case $DECIMAL in
                	10) echo A;;
                	11) echo B;;
                	12) echo C;;
                	13) echo D;;
                	14) echo E;;
                	15) echo F;;
                	esac
		}

	}
	$DECIMAL=(($DECIMAL%16))
done
echo $DECIMAL
